### ISSUE TITLE
Remove the xvkbd dependency

### ISSUE THREAD

**Issue by GaugeK** [sasawat/firefox-ctrl-q-workaround#16]
You're already using xdotool, so why not just use that to send the key? It's one less dependency.

```sh
#!/bin/sh
W="$(xdotool getactivewindow)"
S1="$(xprop -id "$W" | awk -F '"' '/WM_CLASS/{print $4}')"
if [ "$S1" != "Firefox" ] && [ "$S1" != "Firefox Developer Edition" ]; then
	xdotool key --clearmodifiers --window "$W" "ctrl+q"
fi
```

--window and --clearmodifiers are to stop the computer from thinking you aren't holding ctrl anymore.

(I also made it compatible with just plain sh, instead of requiring bash)

(Also^2 it's not recommended to use /bin/bash as bash isn't required to be in /bin (But sh is). However `env` is required to be in /usr/bin by posix so you should do `/usr/bin/env bash`)

**Comment by sasawat** [comment]
I probably made some mistake when I tried, and threw everything out and used xvkbd instead because I wanted it to work.

Anyways, feel free to fork and make a pull request for that change.

I'm contractually not allowed to write open source code right now (dumb, but oh well, they pay me), so I can't make the change myself.

**Comment by GaugeK** [comment]
@sasawat Sorry I took forever to notice this reply, I have just made a pr.
